version: '3'
services:
  meteor:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3002:3000"
    volumes:
      - ${PWD}:/app
  test:
    command: ./start_test.sh
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3002:3000"
    volumes:
      - ${PWD}:/app
