version: '2.2'
services:
  meteor:
    image: inspiraluna/nicokrause_com
    container_name: NicoKrause_com_meteor
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3002:3000"
    volumes:
      - ${PWD}:/app
